openapi: "3.0.0"
info:
  title: T-Shirt Store API
  description: A Collection of REST API for the T-Shirt Store
  version: 1.0.1
  contact:
    url: "https://badjatya.github.io"
    email: architj240@gmail.com

servers:
  - url: "{protocol}://localhost:{port}/api/{version}"
    description: A local host server of the API
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      port:
        enum:
          - 5000
          - 8000
          - 4000
        default: 5000
      version:
        enum:
          - v1
          - v2
        default: v1

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: A basic home route for greeting
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  greeting:
                    type: string
                  dummy:
                    type: boolean
        500:
          description: Internal server error

  /users/signup:
    post:
      tags:
        - Users
      summary: creates a new user, required name, email, password and photo
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - photo
              properties:
                name:
                  type: string
                  description: The name must be less than 40 characters
                email:
                  type: string
                  description: The email must be unique
                password:
                  type: string
                  description: The password must be of 6 characters
                photo:
                  in: formData
                  description: The uploaded file data
                  type: file
                  format: binary
      responses:
        201:
          description: success, user signup's
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secureUrl:
                            type: string
                      createdAt:
                        type: string
                      __v:
                        type: string
        400:
          description: bad request, something went wrong please check all the fields
        500:
          description: Internal server error
